// Word classification for color-coding tiles.
// Only genuine members of each part-of-speech.
// Determiners (the, a, an), prepositions (in, on, to), pronouns (I, we, he),
// and conjunctions (and, but, or) are intentionally left as "other" so they
// don't receive a misleading colour.

const nouns = new Set([
  'dog','cat','boy','girl','teacher','student','sun','tree','food','park',
  'friend','bird','book','bicycle','house','library','family','class',
  'assignment','weather','apple','toy','ball','field','milk','bowl','frog',
  'pond','street','stick','backyard','lesson','door','sunshine','dress',
  'song','mouse','garden','puzzle','drum','kite','picture','festival',
  'dragon','poem','sandcastle','beach','mural','classmates','lunch','mat',
  'ice cream','mailman','soccer','birthday','party','rules','homework',
  'cushion','break','yard','announcement','dinner','trip','picnic','school',
  'question','problem','story','dates','music','hall','performance',
  'weekend','hobby','colour','color','face','letter','cake','newspaper',
  'spring','hill','stars','star','wind','questions','mother','father',
  'child','children','brother','sister','baby','puppy','car','bus','train',
  'map','notebook','cookie','cookies','seed','seeds','rabbit','monkey',
  'butterfly','fish','flowers','flower','animals','zoo','museum',
  'kitchen','shelf','ladder','vase','piano','guitar','violin',
  'breakfast','snack','recess','assembly','bedtime','morning','evening',
  'night','sky','river','valley','mountain','ocean','sea','lake',
  'shore','cave','farm','rocket','recipe','history','culture',
  'popcorn','campfire','fort','frisbee','scooter','bike','nest','nests',
  'tail','art','artwork','rainbow','riddle','rain','storm',
  'thunder','snow','moonlight','sunset','detective','mystery','explorer',
  'treasure','treasures','pizza','candy','bread','fruits','vegetables',
  'cheetah','elephant','owl','fox','dove','jasmine','savanna',
  'champion','town','world','doctor','record','promotion','detour',
  'vacation','exam','award','concert','crowd','audience','team',
  'goal','net','whiteboard','crayons','paper','name','groceries',
  'market','chair','tap','grass','group','groups','idea','ideas',
  'project','places','homeland','cousins','sports','days','words','notes',
  'country','result','results','mom','dad','grandma',
  'books','friends','pictures','songs','assignments','toys','games',
  'animals','stories','jokes','presents','trees','apples','bananas',
  'dumplings','cricket','rope','spot','knee','pen pal',
  'board games','hide and seek','tag','tower','teeth','hands',
  'rice','water','air','table','bed','room','way','place','home',
  'thing','things','people','man','woman','king','queen','prince',
  'princess','hero','village','city','road','path','bridge','wall',
  'roof','window','floor','money','time','year','month','week','day',
  'hour','minute','second','number','word','line','page','chapter',
  'class','test','grade','score','point','side','end','part',
  'area','corner','edge','top','bottom','middle','front','back',
  'hand','foot','feet','head','eye','eyes','ear','ears','nose','mouth',
  'arm','arms','leg','legs','heart','mind','voice','sound','light',
  'fire','stone','rock','sand','dust','leaf','leaves','branch','root',
  'wave','cloud','clouds','fog','ice','flame','smoke','shadow'
]);

const verbs = new Set([
  'is','was','are','were','am','be','been','being',
  'has','had','have','having',
  'do','does','did','doing',
  'can','could','will','would','shall','should','may','might','must',
  'run','runs','ran','running',
  'eat','eats','ate','eating',
  'read','reads','reading',
  'write','writes','wrote','writing',
  'play','plays','played','playing',
  'draw','draws','drew','drawing',
  'build','builds','built','building',
  'go','goes','went','going',
  'make','makes','made','making',
  'kick','kicks','kicked','kicking',
  'chase','chases','chased','chasing',
  'sleep','sleeps','slept','sleeping',
  'bark','barks','barked','barking',
  'dance','dances','danced','dancing',
  'paint','paints','painted','painting',
  'share','shares','shared','sharing',
  'like','likes','liked','liking',
  'see','sees','saw','seeing',
  'sing','sings','sang','singing',
  'cook','cooks','cooked','cooking',
  'drive','drives','drove','driving',
  'visit','visits','visited','visiting',
  'smell','smells','smelled',
  'learn','learns','learned','learning',
  'fall','falls','fell','falling',
  'tell','tells','told','telling',
  'swim','swims','swam','swimming',
  'jump','jumps','jumped','jumping',
  'ride','rides','rode','riding',
  'wag','wags','wagged','wagging',
  'bake','bakes','baked','baking',
  'bloom','blooms','bloomed','blooming',
  'help','helps','helped','helping',
  'climb','climbs','climbed','climbing',
  'count','counts','counted','counting',
  'blow','blows','blew','blowing',
  'laugh','laughs','laughed','laughing',
  'ask','asks','asked','asking',
  'explain','explains','explained','explaining',
  'fetch','fetches','fetched','fetching',
  'listen','listens','listened','listening',
  'prepare','prepares','prepared','preparing',
  'complete','completes','completed','completing',
  'enjoy','enjoys','enjoyed','enjoying',
  'decide','decides','decided','deciding',
  'work','works','worked','working',
  'feel','feels','felt','feeling',
  'join','joins','joined','joining',
  'hear','hears','heard','hearing',
  'fly','flies','flew','flying',
  'shine','shines','shone','shining',
  'open','opens','opened','opening',
  'stop','stops','stopped','stopping',
  'obey','obeys','obeyed',
  'solve','solves','solved','solving',
  'clap','claps','clapped','clapping',
  'cheer','cheers','cheered','cheering',
  'add','adds','added','adding',
  'catch','catches','caught','catching',
  'dig','digs','dug','digging',
  'fix','fixes','fixed','fixing',
  'plant','plants','planted','planting',
  'hop','hops','hopped','hopping',
  'pick','picks','picked','picking',
  'clean','cleans','cleaned','cleaning',
  'buy','buys','bought','buying',
  'swing','swings','swung','swinging',
  'land','lands','landed','landing',
  'arrange','arranges','arranged',
  'await','awaits','awaited',
  'explore','explores','explored','exploring',
  'discover','discovers','discovered',
  'whisper','whispers','whispered',
  'practice','practices','practiced','practicing',
  'present','presents','presented',
  'display','displays','displayed',
  'melt','melts','melted',
  'pet','pets','petted','petting',
  'scare','scares','scared',
  'decorate','decorates','decorated',
  'dodge','dodges','dodged',
  'outsmart','outsmarts',
  'symbolize','symbolizes',
  'receive','receives','received',
  'crash','crashes','crashed',
  'participate','participates',
  'produce','produces','produced',
  'tempt','tempts','tempted',
  'tiptoe','tiptoes','tiptoed',
  'hoot','hoots','hooted',
  'roar','roars','roared',
  'zoom','zooms','zoomed',
  'reflect','reflects','reflected',
  'trumpet','trumpets','trumpeted',
  'attract','attracts','attracted',
  'float','floats','floated',
  'twinkle','twinkles','twinkled',
  'skip','skips','skipped',
  'hurry','hurries','hurried',
  'review','reviews','reviewed',
  'celebrate','celebrates','celebrated',
  'applaud','applauds','applauded',
  'concentrate','concentrates',
  'gather','gathers','gathered',
  'evacuate','evacuates','evacuated',
  'appear','appears','appeared',
  'imagine','imagines','imagined',
  'apologize','apologizes','apologized',
  'forgive','forgives','forgave',
  'train','trains','trained','training',
  'plan','plans','planned','planning',
  'study','studies','studied','studying',
  'thank','thanks','thanked',
  'praise','praises','praised',
  'miss','misses','missed',
  'greet','greets','greeted',
  'arrive','arrives','arrived',
  'finish','finishes','finished',
  'continue','continues','continued',
  'achieve','achieves','achieved',
  'improve','improves','improved',
  'become','becomes','became',
  'break','breaks','broke',
  'stay','stays','stayed',
  'shop','shops','shopped',
  'move','moves','moved',
  'score','scores','scored',
  'release','releases','released',
  'recite','recites','recited',
  'chirp','chirps','chirped',
  'purr','purrs','purred',
  'howl','howls','howled',
  'flutter','flutters','fluttered',
  'flow','flows','flowed',
  'watch','watches','watched',
  'walk','walks','walked',
  'talk','talks','talked',
  'chat','chats','chatted',
  'argue','argues','argued',
  'wash','washes','washed',
  'brush','brushes','brushed',
  'love','loves','loved',
  'wear','wears','wore',
  'cry','cries','cried',
  'set','sets','setting',
  'wait','waits','waited',
  'rise','rises','rose',
  'wake','wakes','woke',
  'hang','hangs','hung',
  'label','labels','labeled',
  'water','waters','watered',
  'organize','organizes','organized',
  'mow','mows','mowed',
  'need','needs','needed',
  'want','wants','wanted',
  'start','starts','started',
  'turn','turns','turned',
  'use','uses','used',
  'bring','brings','brought',
  'take','takes','took',
  'give','gives','gave',
  'find','finds','found',
  'know','knows','knew',
  'think','thinks','thought',
  'come','comes','came',
  'say','says','said',
  'look','looks','looked',
  'get','gets','got',
  'try','tries','tried',
  'leave','leaves','left',
  'put','puts',
  'keep','keeps','kept',
  'let','lets',
  'show','shows','showed',
  'begin','begins','began',
  'seem','seems','seemed',
  'call','calls','called',
  'carry','carries','carried',
  'hold','holds','held',
  'pass','passes','passed',
  'sit','sits','sat',
  'stand','stands','stood',
  'lose','loses','lost',
  'pay','pays','paid',
  'meet','meets','met',
  'send','sends','sent',
  'spend','spends','spent',
  'grow','grows','grew',
  'win','wins','won',
  'teach','teaches','taught',
  'lend','lends','lent',
  'bite','bites','bit',
  'cut','cuts',
  'choose','chooses','chose',
  'drink','drinks','drank',
  'speak','speaks','spoke',
  'ring','rings','rang',
  'hide','hides','hid',
  'rustle','rustles','rustled','rustling'
]);

const adjectives = new Set([
  'huge','small','red','blue','warm','quiet','empty','fast','bright',
  'tasty','kind','gentle','colorful','tall','green','cold','soft',
  'delicious','full','interesting','fun','educational','beautiful',
  'challenging','difficult','excited','new','big','high','pretty',
  'funny','happy','hard','sweet','juicy','round','hot','favourite',
  'favorite','shiny','little','brave','smart','busy','elderly',
  'calm','attentive','detailed','playful','thoughtful','creative',
  'cheerful','wonderful','amazing','fantastic','incredible','spectacular',
  'extraordinary','excellent','remarkable','engaging','unwavering',
  'slippery','tricky','fascinating','joyful','skilled',
  'talented','strong','powerful','peaceful','fragrant','wise','clever',
  'loud','fresh','fluffy','lazy','ancient','massive','adventurous',
  'quick','brown','vibrant','spacious','sunny','steep',
  'dark','broken','leaky','early','late','young','old','long',
  'short','wide','narrow','thick','thin','deep','shallow',
  'heavy','light','clean','dirty','dry','wet','clear','cloudy',
  'noisy','silent','safe','dangerous','easy','simple','complex',
  'free','expensive','cheap','rich','poor','weak',
  'healthy','sick','tired','nervous','proud','grateful',
  'correct','tough','unusual','unique','stunning','historical',
  'magnificent','graceful','musical','artistic',
  'great','nice','good','bad','better','best','worse','worst',
  'cool','damp','fine','lovely','perfect','wonderful','terrible',
  'important','main','special','different','same','other'
]);

const adverbs = new Set([
  'quickly','slowly','happily','quietly','brightly','cheerfully',
  'eagerly','very','heavily','patiently','always','often',
  'carefully','beautifully','clearly','softly','loudly','gently',
  'gracefully','enthusiastically','diligently','swiftly','curiously',
  'confidently','proudly','gratefully','lazily','joyfully','bravely',
  'kindly','generously','vibrantly','silently','precisely','excitedly',
  'skillfully','contentedly','steadily','cleverly','melodiously',
  'regularly','equally','playfully','yesterday','today','daily',
  'never','sometimes','usually','already','still','just','soon',
  'now','then','together','apart','inside','outside',
  'really','quite','too','almost','also','even','only',
  'again','finally','suddenly','eventually','sincerely','politely',
  'willingly','promptly','thoroughly','attentively','warmly',
  'deeply','significantly','remarkably','well','hard','fast',
  'not','extremely','particularly','exceptionally','especially'
]);

export function getWordClass(word) {
  const clean = word
    .toLowerCase()
    .replace(/[.!?,;:'\u2018\u2019\u201C\u201D"]/g, '');
  if (adverbs.has(clean)) return 'adverb';
  if (verbs.has(clean)) return 'verb';
  if (adjectives.has(clean)) return 'adjective';
  if (nouns.has(clean)) return 'noun';
  // Words ending in -ly (4+ chars) are likely adverbs
  if (clean.endsWith('ly') && clean.length > 3) return 'adverb';
  // Capitalised words (not sentence-start) are likely proper nouns
  if (/^[A-Z]/.test(word)) return 'noun';
  return 'other';
}

export function getWordRole(word, index, correctArray) {
  if (index === 0) return 'subject';
  if (index === 1) return 'verb';
  if (index > 1 && index < correctArray.length - 1) return 'object';
  return 'end';
}

export function annotateSentence(sentence) {
  const words = sentence.split(' ');
  return words.map((w, i) => `${w} [${getWordClass(w)}/${getWordRole(w, i, words)}]`).join(' ');
}
