const nouns = new Set(['dog','cat','boy','girl','teacher','student','story','sun','tree','food','park','friend','bird','book','bicycle','house','library','family','class','assignment','weather','apple','toy','ball','field','milk','bowl','frog','pond','street','stick','backyard','lesson','door','sunshine','dress','song','mouse','garden','puzzle','drum','kite','picture','family','festival','dragon','poem','sandcastle','beach','mural','books','classmates','lunch','mat','pictures','song','ice cream','green','mailman','soccer','friends','dances','paints','shares','birthday','party','rules','homework','cushion','break','yard','announcement','dinner','books','assignments','trip','picnic','bicycle','school','picture','question','problem','book','story','dates','class','song','dance','music','hall','performance','weekend','hobby','colour','tree','face','letter','cake','newspaper','hide and seek','mouse','spring','face','friend','hill','stars','wind','laugh','questions']);
const verbs = new Set(['is','was','are','run','runs','ran','eat','eats','ate','read','reads','write','writes','play','plays','draw','draws','build','builds','go','goes','went','make','makes','made','kick','kicks','chase','chases','had','can','chased','would','like','have','sleeps','barks','plays','dances','paints','shares','build','like','read','see','ate','went','eats','did','enjoy','sings','clapped','cheered','like','add','runs','play','sings','barks','ate','went','eats','see','shines','sing','draw','cooks','drives','visit','smells','kicks','dances','build','learn','falls','share','tells','run','is','are','swim','jump','sings','rides','eat','wags','build','write','bakes','reads','play','chases','bloom','draws','helps','climb','count','blows','laugh','asks','explained','helps','slept','play','fetched','listened','prepared','completed','enjoyed','decided','rode','painted','asked','worked','felt','reads','shares','sings','learns','join','hear','was','sleeping','eat','flies','reads','play','runs','read','is','go','sees','shines','sing','draw','cooks','drives','visit','smells','kicks','dances','build','learn','falls','share','tells','run','is','are','swim','jump','sings','rides','eat','wags','build','write','bakes','reads','play','chases','bloom','draws','helps','climb','count','blows','laugh','asks']);
const adjectives = new Set(['huge','small','red','blue','warm','quiet','empty','fast','bright','tasty','kind','gentle','colorful','tall','green','cold','champion','very','heavily','all','so','cold','which','these','clearly','patiently','always','quietly','soft','often','our','eagerly','carefully','delicious','full','interesting','fun','educational','so','warm','happily','beautiful','challenging','difficult','excited','new','about','with','from','learns','like','can','hear','amazing','sleeping','big','high','big','with','every','carefully','on','new','hot','bright','favourite','big','red','round','high','together','pretty','a','funny','happy','hard','gracefully','a','sweet','hard','new','blue','juicy','blue','quickly','over','a','happy','his','fast','lunch','its','nests','a','a','the','hide','the','in','a','funny','her','the','the','the','together','the','asks']);
const adverbs = new Set(['quickly','slowly','happily','quietly','brightly','cheerfully','eagerly','very','heavily','should','obey','that','could','not','stop','of','do','enjoy','doing','explained','and','patiently','always','helps','with','quietly','slept','on','often','play','during','eagerly','fetched','in','listened','carefully','to','prepared','a','for','was','and','of','carefully','completed','all','on','enjoyed','a','and','was','that','we','decided','to','happily','rode','his','to','carefully','painted','a','asked','a','during','worked','together','to','solve','felt','as','opened','reads','a','about','shares','with','her','sings','a','from','learns','a','from','would','like','to','our','can','hear','from','that','was','an','is','on','like','to','and','like','to','on','add','some','to','runs','play','sings','barks','ate','went','eats','did','enjoy','sings','very','at','end','of','concert','audience','and','and','like','to','on','some','to','cat','I','to','apples','and','bird','high','in','sky','teacher','a','book','in','play','games','our','at','dog','in','park','read','a','book','cat','on','table','go','to','every','day','sees','a','bird','sun','brightly','today','sing','in','morning','pictures','with','cooks','for','us','drives','car','visit','on','weekends','smells','kicks','ball','dances','build','a','learn','words','rain','softly','share','happily','teacher','stories','in','field','book','interesting','are','and','sky','fish','I','over','rope','sings','song','rides','bike','eat','together','dog','tail','build','write','letter','bakes','cake','reads','newspaper','play','and','cat','chases','flowers','in','draws','face','helps','friend','climb','hill','count','stars','wind','gently','friends','together','teacher','questions']);

export function getWordClass(word) {
  // Remove punctuation including straight and curly apostrophes
  const clean = word
    .toLowerCase()
    .replace(/[.!?'\u2019]/g, '');
  if (adverbs.has(clean) || clean.endsWith('ly')) return 'adverb';
  if (verbs.has(clean)) return 'verb';
  if (adjectives.has(clean)) return 'adjective';
  if (nouns.has(clean) || /^[A-Z]/.test(word)) return 'noun';
  return 'other';
}
export function getWordRole(word,index,correctArray) {
  if(index===0) return 'subject';
  if(index===1) return 'verb';
  if(index>1 && index<correctArray.length-1) return 'object';
  return 'end';
}
export function annotateSentence(sentence) {
  const words = sentence.split(' ');
  return words.map((w, i) => `${w} [${getWordClass(w)}/${getWordRole(w, i, words)}]`).join(' ');
}
